/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminBoxItem } from './admin-box-item';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminMachineItem } from './admin-machine-item';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityAuditLog } from './admin-observability-audit-log';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityCommands } from './admin-observability-commands';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityCorrelation } from './admin-observability-correlation';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityExternalLinks } from './admin-observability-external-links';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityOperation } from './admin-observability-operation';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityResourceSummary } from './admin-observability-resource-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityS3Object } from './admin-observability-s3-object';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilitySourceStatus } from './admin-observability-source-status';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityTimelineEvent } from './admin-observability-timeline-event';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityXLog } from './admin-observability-xlog';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminRunnerItem } from './admin-runner-item';
// May contain unused imports in some cases
// @ts-ignore
import type { LogEntry } from './log-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { MetricsResponse } from './metrics-response';
// May contain unused imports in some cases
// @ts-ignore
import type { TraceSpan } from './trace-span';

export interface AdminObservabilityInvestigateResponse {
    'resource': AdminObservabilityResourceSummary;
    'correlation': AdminObservabilityCorrelation;
    'sources': Array<AdminObservabilitySourceStatus>;
    'traceSpans': Array<TraceSpan>;
    'logs': Array<LogEntry>;
    'metrics': MetricsResponse;
    'boxes': Array<AdminBoxItem>;
    'runners': Array<AdminRunnerItem>;
    'machines': Array<AdminMachineItem>;
    'auditLogs': Array<AdminObservabilityAuditLog>;
    'xlogs': Array<AdminObservabilityXLog>;
    's3Objects': Array<AdminObservabilityS3Object>;
    'timeline': Array<AdminObservabilityTimelineEvent>;
    'operations': Array<AdminObservabilityOperation>;
    'commands': AdminObservabilityCommands;
    'externalLinks': AdminObservabilityExternalLinks;
}

