/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewBoxes } from './admin-overview-boxes';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewCluster } from './admin-overview-cluster';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminOverviewRunners } from './admin-overview-runners';

export interface AdminOverview {
    /**
     * Total number of users
     */
    'users': number;
    /**
     * Number of active (started) boxes
     */
    'activeBoxes': number;
    'boxes': AdminOverviewBoxes;
    'runners': AdminOverviewRunners;
    'cluster': AdminOverviewCluster;
}

