/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminOverviewCluster {
    /**
     * Average CPU utilisation across all runners (0–1)
     */
    'cpuUtil': number;
    /**
     * Average CPU oversell ratio (allocated / capacity); 0 when no capacity
     */
    'oversell': number;
}

