/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminJobOverview {
    'id': string;
    'type': string;
    'status': string;
    'runnerId'?: string | null;
    'resourceType': string;
    'resourceId': string;
    'createdAt'?: Date | null;
    'startedAt'?: Date | null;
    'finishedAt'?: Date | null;
    'durationMs'?: number | null;
    'errorCategory'?: AdminJobOverviewErrorCategoryEnum | null;
    'observedAt'?: Date | null;
}

export const AdminJobOverviewErrorCategoryEnum = {
    CAPACITY: 'capacity',
    NETWORK: 'network',
    IMAGE: 'image',
    STORAGE: 'storage',
    TIMEOUT: 'timeout',
    UNKNOWN: 'unknown',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminJobOverviewErrorCategoryEnum = typeof AdminJobOverviewErrorCategoryEnum[keyof typeof AdminJobOverviewErrorCategoryEnum];


