/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminObservabilitySourceStatus {
    'source': AdminObservabilitySourceStatusSourceEnum;
    'state': AdminObservabilitySourceStatusStateEnum;
    'message'?: string;
    'count'?: number;
}

export const AdminObservabilitySourceStatusSourceEnum = {
    CLICKHOUSE: 'clickhouse',
    CLICKSTACK: 'clickstack',
    POSTGRES: 'postgres',
    AUDIT: 'audit',
    CLOUDWATCH: 'cloudwatch',
    S3: 's3',
    XLOG: 'xlog',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminObservabilitySourceStatusSourceEnum = typeof AdminObservabilitySourceStatusSourceEnum[keyof typeof AdminObservabilitySourceStatusSourceEnum];
export const AdminObservabilitySourceStatusStateEnum = {
    AVAILABLE: 'available',
    MISSING: 'missing',
    STALE: 'stale',
    NOT_CONFIGURED: 'not_configured',
    ERROR: 'error',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminObservabilitySourceStatusStateEnum = typeof AdminObservabilitySourceStatusStateEnum[keyof typeof AdminObservabilitySourceStatusStateEnum];


