/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminObservabilityBackendStatusDto {
    /**
     * Whether ClickHouse/ClickStack query configuration is present
     */
    'configured': boolean;
    'state': AdminObservabilityBackendStatusDtoStateEnum;
    'message'?: string;
}

export const AdminObservabilityBackendStatusDtoStateEnum = {
    MISSING: 'missing',
    CONFIGURED: 'configured',
    RECEIVING: 'receiving',
    STALE: 'stale',
    ERROR: 'error',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminObservabilityBackendStatusDtoStateEnum = typeof AdminObservabilityBackendStatusDtoStateEnum[keyof typeof AdminObservabilityBackendStatusDtoStateEnum];


