/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminObservabilityLayerSignalsDto } from './admin-observability-layer-signals-dto';

export interface AdminObservabilityLayerStatusDto {
    'layer': AdminObservabilityLayerStatusDtoLayerEnum;
    'state': AdminObservabilityLayerStatusDtoStateEnum;
    'signals': AdminObservabilityLayerSignalsDto;
    'lastSeen'?: string;
}

export const AdminObservabilityLayerStatusDtoLayerEnum = {
    API: 'api',
    RUNNER: 'runner',
    EC2_HOST: 'ec2_host',
    BOX: 'box',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminObservabilityLayerStatusDtoLayerEnum = typeof AdminObservabilityLayerStatusDtoLayerEnum[keyof typeof AdminObservabilityLayerStatusDtoLayerEnum];
export const AdminObservabilityLayerStatusDtoStateEnum = {
    MISSING: 'missing',
    CONFIGURED: 'configured',
    RECEIVING: 'receiving',
    STALE: 'stale',
    ERROR: 'error',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type AdminObservabilityLayerStatusDtoStateEnum = typeof AdminObservabilityLayerStatusDtoStateEnum[keyof typeof AdminObservabilityLayerStatusDtoStateEnum];


