/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ApiKeyResponse {
    /**
     * The name of the API key
     */
    'name': string;
    /**
     * The API key value
     */
    'value': string;
    /**
     * When the API key was created
     */
    'createdAt': Date;
    /**
     * The list of organization resource permissions assigned to the API key
     */
    'permissions': Array<ApiKeyResponsePermissionsEnum>;
    /**
     * When the API key expires
     */
    'expiresAt': Date | null;
}

export const ApiKeyResponsePermissionsEnum = {
    WRITE_REGISTRIES: 'write:registries',
    DELETE_REGISTRIES: 'delete:registries',
    WRITE_TEMPLATES: 'write:templates',
    DELETE_TEMPLATES: 'delete:templates',
    WRITE_BOXES: 'write:boxes',
    DELETE_BOXES: 'delete:boxes',
    READ_VOLUMES: 'read:volumes',
    WRITE_VOLUMES: 'write:volumes',
    DELETE_VOLUMES: 'delete:volumes',
    WRITE_REGIONS: 'write:regions',
    DELETE_REGIONS: 'delete:regions',
    READ_RUNNERS: 'read:runners',
    WRITE_RUNNERS: 'write:runners',
    DELETE_RUNNERS: 'delete:runners',
    READ_AUDIT_LOGS: 'read:audit_logs',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type ApiKeyResponsePermissionsEnum = typeof ApiKeyResponsePermissionsEnum[keyof typeof ApiKeyResponsePermissionsEnum];


