/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The desired state of the box
 */

export const BoxDesiredState = {
    DESTROYED: 'destroyed',
    STARTED: 'started',
    STOPPED: 'stopped',
    RESIZED: 'resized',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type BoxDesiredState = typeof BoxDesiredState[keyof typeof BoxDesiredState];



