/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateUser {
    'id': string;
    'name': string;
    'email'?: string;
    'defaultOrganizationDefaultRegionId'?: string;
    /**
     * Deprecated alias for defaultOrganizationDefaultRegionId.
     * @deprecated
     */
    'personalOrganizationDefaultRegionId'?: string;
    'role'?: CreateUserRoleEnum;
    'emailVerified'?: boolean;
}

export const CreateUserRoleEnum = {
    ADMIN: 'admin',
    USER: 'user',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type CreateUserRoleEnum = typeof CreateUserRoleEnum[keyof typeof CreateUserRoleEnum];


