/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TraceSpan {
    /**
     * Trace identifier
     */
    'traceId': string;
    /**
     * Span identifier
     */
    'spanId': string;
    /**
     * Parent span identifier
     */
    'parentSpanId'?: string;
    /**
     * Span name
     */
    'spanName': string;
    /**
     * Emitting service name (e.g. boxlite-api, boxlite-runner, box-<id>)
     */
    'serviceName'?: string;
    /**
     * Resolved emitting layer: api | runner | ec2_host | box
     */
    'layer'?: string;
    /**
     * Span start timestamp
     */
    'timestamp': string;
    /**
     * Span duration in nanoseconds
     */
    'durationNs': number;
    /**
     * Span attributes
     */
    'spanAttributes': { [key: string]: string; };
    /**
     * Status code of the span
     */
    'statusCode'?: string;
    /**
     * Status message
     */
    'statusMessage'?: string;
}

