/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AdminOrganizationOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminOrganizationOverview{}

// AdminOrganizationOverview struct for AdminOrganizationOverview
type AdminOrganizationOverview struct {
	OrganizationId string `json:"organizationId"`
	Name string `json:"name"`
	MemberCount float32 `json:"memberCount"`
	BoxCount float32 `json:"boxCount"`
	ImpactState string `json:"impactState"`
	ObservedAt time.Time `json:"observedAt"`
	AdditionalProperties map[string]interface{}
}

type _AdminOrganizationOverview AdminOrganizationOverview

// NewAdminOrganizationOverview instantiates a new AdminOrganizationOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminOrganizationOverview(organizationId string, name string, memberCount float32, boxCount float32, impactState string, observedAt time.Time) *AdminOrganizationOverview {
	this := AdminOrganizationOverview{}
	this.OrganizationId = organizationId
	this.Name = name
	this.MemberCount = memberCount
	this.BoxCount = boxCount
	this.ImpactState = impactState
	this.ObservedAt = observedAt
	return &this
}

// NewAdminOrganizationOverviewWithDefaults instantiates a new AdminOrganizationOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminOrganizationOverviewWithDefaults() *AdminOrganizationOverview {
	this := AdminOrganizationOverview{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *AdminOrganizationOverview) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *AdminOrganizationOverview) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetName returns the Name field value
func (o *AdminOrganizationOverview) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdminOrganizationOverview) SetName(v string) {
	o.Name = v
}

// GetMemberCount returns the MemberCount field value
func (o *AdminOrganizationOverview) GetMemberCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetMemberCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberCount, true
}

// SetMemberCount sets field value
func (o *AdminOrganizationOverview) SetMemberCount(v float32) {
	o.MemberCount = v
}

// GetBoxCount returns the BoxCount field value
func (o *AdminOrganizationOverview) GetBoxCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BoxCount
}

// GetBoxCountOk returns a tuple with the BoxCount field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetBoxCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxCount, true
}

// SetBoxCount sets field value
func (o *AdminOrganizationOverview) SetBoxCount(v float32) {
	o.BoxCount = v
}

// GetImpactState returns the ImpactState field value
func (o *AdminOrganizationOverview) GetImpactState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImpactState
}

// GetImpactStateOk returns a tuple with the ImpactState field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetImpactStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImpactState, true
}

// SetImpactState sets field value
func (o *AdminOrganizationOverview) SetImpactState(v string) {
	o.ImpactState = v
}

// GetObservedAt returns the ObservedAt field value
func (o *AdminOrganizationOverview) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationOverview) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *AdminOrganizationOverview) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

func (o AdminOrganizationOverview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminOrganizationOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["name"] = o.Name
	toSerialize["memberCount"] = o.MemberCount
	toSerialize["boxCount"] = o.BoxCount
	toSerialize["impactState"] = o.ImpactState
	toSerialize["observedAt"] = o.ObservedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminOrganizationOverview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationId",
		"name",
		"memberCount",
		"boxCount",
		"impactState",
		"observedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminOrganizationOverview := _AdminOrganizationOverview{}

	err = json.Unmarshal(data, &varAdminOrganizationOverview)

	if err != nil {
		return err
	}

	*o = AdminOrganizationOverview(varAdminOrganizationOverview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "memberCount")
		delete(additionalProperties, "boxCount")
		delete(additionalProperties, "impactState")
		delete(additionalProperties, "observedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminOrganizationOverview struct {
	value *AdminOrganizationOverview
	isSet bool
}

func (v NullableAdminOrganizationOverview) Get() *AdminOrganizationOverview {
	return v.value
}

func (v *NullableAdminOrganizationOverview) Set(val *AdminOrganizationOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminOrganizationOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminOrganizationOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminOrganizationOverview(val *AdminOrganizationOverview) *NullableAdminOrganizationOverview {
	return &NullableAdminOrganizationOverview{value: val, isSet: true}
}

func (v NullableAdminOrganizationOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminOrganizationOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


