/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AdminOrganizationMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminOrganizationMember{}

// AdminOrganizationMember struct for AdminOrganizationMember
type AdminOrganizationMember struct {
	UserId string `json:"userId"`
	Email string `json:"email"`
	DisplayName string `json:"displayName"`
	OrganizationRole string `json:"organizationRole"`
	JoinedAt time.Time `json:"joinedAt"`
	AdditionalProperties map[string]interface{}
}

type _AdminOrganizationMember AdminOrganizationMember

// NewAdminOrganizationMember instantiates a new AdminOrganizationMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminOrganizationMember(userId string, email string, displayName string, organizationRole string, joinedAt time.Time) *AdminOrganizationMember {
	this := AdminOrganizationMember{}
	this.UserId = userId
	this.Email = email
	this.DisplayName = displayName
	this.OrganizationRole = organizationRole
	this.JoinedAt = joinedAt
	return &this
}

// NewAdminOrganizationMemberWithDefaults instantiates a new AdminOrganizationMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminOrganizationMemberWithDefaults() *AdminOrganizationMember {
	this := AdminOrganizationMember{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AdminOrganizationMember) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationMember) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AdminOrganizationMember) SetUserId(v string) {
	o.UserId = v
}

// GetEmail returns the Email field value
func (o *AdminOrganizationMember) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationMember) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AdminOrganizationMember) SetEmail(v string) {
	o.Email = v
}

// GetDisplayName returns the DisplayName field value
func (o *AdminOrganizationMember) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationMember) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AdminOrganizationMember) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetOrganizationRole returns the OrganizationRole field value
func (o *AdminOrganizationMember) GetOrganizationRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationRole
}

// GetOrganizationRoleOk returns a tuple with the OrganizationRole field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationMember) GetOrganizationRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationRole, true
}

// SetOrganizationRole sets field value
func (o *AdminOrganizationMember) SetOrganizationRole(v string) {
	o.OrganizationRole = v
}

// GetJoinedAt returns the JoinedAt field value
func (o *AdminOrganizationMember) GetJoinedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.JoinedAt
}

// GetJoinedAtOk returns a tuple with the JoinedAt field value
// and a boolean to check if the value has been set.
func (o *AdminOrganizationMember) GetJoinedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JoinedAt, true
}

// SetJoinedAt sets field value
func (o *AdminOrganizationMember) SetJoinedAt(v time.Time) {
	o.JoinedAt = v
}

func (o AdminOrganizationMember) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminOrganizationMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["email"] = o.Email
	toSerialize["displayName"] = o.DisplayName
	toSerialize["organizationRole"] = o.OrganizationRole
	toSerialize["joinedAt"] = o.JoinedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminOrganizationMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"email",
		"displayName",
		"organizationRole",
		"joinedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminOrganizationMember := _AdminOrganizationMember{}

	err = json.Unmarshal(data, &varAdminOrganizationMember)

	if err != nil {
		return err
	}

	*o = AdminOrganizationMember(varAdminOrganizationMember)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "userId")
		delete(additionalProperties, "email")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "organizationRole")
		delete(additionalProperties, "joinedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminOrganizationMember struct {
	value *AdminOrganizationMember
	isSet bool
}

func (v NullableAdminOrganizationMember) Get() *AdminOrganizationMember {
	return v.value
}

func (v *NullableAdminOrganizationMember) Set(val *AdminOrganizationMember) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminOrganizationMember) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminOrganizationMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminOrganizationMember(val *AdminOrganizationMember) *NullableAdminOrganizationMember {
	return &NullableAdminOrganizationMember{value: val, isSet: true}
}

func (v NullableAdminOrganizationMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminOrganizationMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


