/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityLayerStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityLayerStatusDto{}

// AdminObservabilityLayerStatusDto struct for AdminObservabilityLayerStatusDto
type AdminObservabilityLayerStatusDto struct {
	Layer string `json:"layer"`
	State string `json:"state"`
	Signals AdminObservabilityLayerSignalsDto `json:"signals"`
	LastSeen *string `json:"lastSeen,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityLayerStatusDto AdminObservabilityLayerStatusDto

// NewAdminObservabilityLayerStatusDto instantiates a new AdminObservabilityLayerStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityLayerStatusDto(layer string, state string, signals AdminObservabilityLayerSignalsDto) *AdminObservabilityLayerStatusDto {
	this := AdminObservabilityLayerStatusDto{}
	this.Layer = layer
	this.State = state
	this.Signals = signals
	return &this
}

// NewAdminObservabilityLayerStatusDtoWithDefaults instantiates a new AdminObservabilityLayerStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityLayerStatusDtoWithDefaults() *AdminObservabilityLayerStatusDto {
	this := AdminObservabilityLayerStatusDto{}
	return &this
}

// GetLayer returns the Layer field value
func (o *AdminObservabilityLayerStatusDto) GetLayer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Layer
}

// GetLayerOk returns a tuple with the Layer field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerStatusDto) GetLayerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Layer, true
}

// SetLayer sets field value
func (o *AdminObservabilityLayerStatusDto) SetLayer(v string) {
	o.Layer = v
}

// GetState returns the State field value
func (o *AdminObservabilityLayerStatusDto) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerStatusDto) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *AdminObservabilityLayerStatusDto) SetState(v string) {
	o.State = v
}

// GetSignals returns the Signals field value
func (o *AdminObservabilityLayerStatusDto) GetSignals() AdminObservabilityLayerSignalsDto {
	if o == nil {
		var ret AdminObservabilityLayerSignalsDto
		return ret
	}

	return o.Signals
}

// GetSignalsOk returns a tuple with the Signals field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerStatusDto) GetSignalsOk() (*AdminObservabilityLayerSignalsDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signals, true
}

// SetSignals sets field value
func (o *AdminObservabilityLayerStatusDto) SetSignals(v AdminObservabilityLayerSignalsDto) {
	o.Signals = v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *AdminObservabilityLayerStatusDto) GetLastSeen() string {
	if o == nil || IsNil(o.LastSeen) {
		var ret string
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerStatusDto) GetLastSeenOk() (*string, bool) {
	if o == nil || IsNil(o.LastSeen) {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *AdminObservabilityLayerStatusDto) HasLastSeen() bool {
	if o != nil && !IsNil(o.LastSeen) {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given string and assigns it to the LastSeen field.
func (o *AdminObservabilityLayerStatusDto) SetLastSeen(v string) {
	o.LastSeen = &v
}

func (o AdminObservabilityLayerStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityLayerStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["layer"] = o.Layer
	toSerialize["state"] = o.State
	toSerialize["signals"] = o.Signals
	if !IsNil(o.LastSeen) {
		toSerialize["lastSeen"] = o.LastSeen
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityLayerStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"layer",
		"state",
		"signals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityLayerStatusDto := _AdminObservabilityLayerStatusDto{}

	err = json.Unmarshal(data, &varAdminObservabilityLayerStatusDto)

	if err != nil {
		return err
	}

	*o = AdminObservabilityLayerStatusDto(varAdminObservabilityLayerStatusDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "layer")
		delete(additionalProperties, "state")
		delete(additionalProperties, "signals")
		delete(additionalProperties, "lastSeen")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityLayerStatusDto struct {
	value *AdminObservabilityLayerStatusDto
	isSet bool
}

func (v NullableAdminObservabilityLayerStatusDto) Get() *AdminObservabilityLayerStatusDto {
	return v.value
}

func (v *NullableAdminObservabilityLayerStatusDto) Set(val *AdminObservabilityLayerStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityLayerStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityLayerStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityLayerStatusDto(val *AdminObservabilityLayerStatusDto) *NullableAdminObservabilityLayerStatusDto {
	return &NullableAdminObservabilityLayerStatusDto{value: val, isSet: true}
}

func (v NullableAdminObservabilityLayerStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityLayerStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


