/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityResourceSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityResourceSummary{}

// AdminObservabilityResourceSummary struct for AdminObservabilityResourceSummary
type AdminObservabilityResourceSummary struct {
	Type string `json:"type"`
	Title string `json:"title"`
	Subtitle *string `json:"subtitle,omitempty"`
	State *string `json:"state,omitempty"`
	Owner *string `json:"owner,omitempty"`
	Identifiers map[string]interface{} `json:"identifiers,omitempty"`
	TimeRange map[string]interface{} `json:"timeRange,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityResourceSummary AdminObservabilityResourceSummary

// NewAdminObservabilityResourceSummary instantiates a new AdminObservabilityResourceSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityResourceSummary(type_ string, title string) *AdminObservabilityResourceSummary {
	this := AdminObservabilityResourceSummary{}
	this.Type = type_
	this.Title = title
	return &this
}

// NewAdminObservabilityResourceSummaryWithDefaults instantiates a new AdminObservabilityResourceSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityResourceSummaryWithDefaults() *AdminObservabilityResourceSummary {
	this := AdminObservabilityResourceSummary{}
	return &this
}

// GetType returns the Type field value
func (o *AdminObservabilityResourceSummary) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdminObservabilityResourceSummary) SetType(v string) {
	o.Type = v
}

// GetTitle returns the Title field value
func (o *AdminObservabilityResourceSummary) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AdminObservabilityResourceSummary) SetTitle(v string) {
	o.Title = v
}

// GetSubtitle returns the Subtitle field value if set, zero value otherwise.
func (o *AdminObservabilityResourceSummary) GetSubtitle() string {
	if o == nil || IsNil(o.Subtitle) {
		var ret string
		return ret
	}
	return *o.Subtitle
}

// GetSubtitleOk returns a tuple with the Subtitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetSubtitleOk() (*string, bool) {
	if o == nil || IsNil(o.Subtitle) {
		return nil, false
	}
	return o.Subtitle, true
}

// HasSubtitle returns a boolean if a field has been set.
func (o *AdminObservabilityResourceSummary) HasSubtitle() bool {
	if o != nil && !IsNil(o.Subtitle) {
		return true
	}

	return false
}

// SetSubtitle gets a reference to the given string and assigns it to the Subtitle field.
func (o *AdminObservabilityResourceSummary) SetSubtitle(v string) {
	o.Subtitle = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *AdminObservabilityResourceSummary) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *AdminObservabilityResourceSummary) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *AdminObservabilityResourceSummary) SetState(v string) {
	o.State = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *AdminObservabilityResourceSummary) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *AdminObservabilityResourceSummary) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *AdminObservabilityResourceSummary) SetOwner(v string) {
	o.Owner = &v
}

// GetIdentifiers returns the Identifiers field value if set, zero value otherwise.
func (o *AdminObservabilityResourceSummary) GetIdentifiers() map[string]interface{} {
	if o == nil || IsNil(o.Identifiers) {
		var ret map[string]interface{}
		return ret
	}
	return o.Identifiers
}

// GetIdentifiersOk returns a tuple with the Identifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetIdentifiersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Identifiers) {
		return map[string]interface{}{}, false
	}
	return o.Identifiers, true
}

// HasIdentifiers returns a boolean if a field has been set.
func (o *AdminObservabilityResourceSummary) HasIdentifiers() bool {
	if o != nil && !IsNil(o.Identifiers) {
		return true
	}

	return false
}

// SetIdentifiers gets a reference to the given map[string]interface{} and assigns it to the Identifiers field.
func (o *AdminObservabilityResourceSummary) SetIdentifiers(v map[string]interface{}) {
	o.Identifiers = v
}

// GetTimeRange returns the TimeRange field value if set, zero value otherwise.
func (o *AdminObservabilityResourceSummary) GetTimeRange() map[string]interface{} {
	if o == nil || IsNil(o.TimeRange) {
		var ret map[string]interface{}
		return ret
	}
	return o.TimeRange
}

// GetTimeRangeOk returns a tuple with the TimeRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityResourceSummary) GetTimeRangeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TimeRange) {
		return map[string]interface{}{}, false
	}
	return o.TimeRange, true
}

// HasTimeRange returns a boolean if a field has been set.
func (o *AdminObservabilityResourceSummary) HasTimeRange() bool {
	if o != nil && !IsNil(o.TimeRange) {
		return true
	}

	return false
}

// SetTimeRange gets a reference to the given map[string]interface{} and assigns it to the TimeRange field.
func (o *AdminObservabilityResourceSummary) SetTimeRange(v map[string]interface{}) {
	o.TimeRange = v
}

func (o AdminObservabilityResourceSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityResourceSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["title"] = o.Title
	if !IsNil(o.Subtitle) {
		toSerialize["subtitle"] = o.Subtitle
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Identifiers) {
		toSerialize["identifiers"] = o.Identifiers
	}
	if !IsNil(o.TimeRange) {
		toSerialize["timeRange"] = o.TimeRange
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityResourceSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityResourceSummary := _AdminObservabilityResourceSummary{}

	err = json.Unmarshal(data, &varAdminObservabilityResourceSummary)

	if err != nil {
		return err
	}

	*o = AdminObservabilityResourceSummary(varAdminObservabilityResourceSummary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "title")
		delete(additionalProperties, "subtitle")
		delete(additionalProperties, "state")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "identifiers")
		delete(additionalProperties, "timeRange")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityResourceSummary struct {
	value *AdminObservabilityResourceSummary
	isSet bool
}

func (v NullableAdminObservabilityResourceSummary) Get() *AdminObservabilityResourceSummary {
	return v.value
}

func (v *NullableAdminObservabilityResourceSummary) Set(val *AdminObservabilityResourceSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityResourceSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityResourceSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityResourceSummary(val *AdminObservabilityResourceSummary) *NullableAdminObservabilityResourceSummary {
	return &NullableAdminObservabilityResourceSummary{value: val, isSet: true}
}

func (v NullableAdminObservabilityResourceSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityResourceSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


