/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityLayerSignalsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityLayerSignalsDto{}

// AdminObservabilityLayerSignalsDto struct for AdminObservabilityLayerSignalsDto
type AdminObservabilityLayerSignalsDto struct {
	Logs string `json:"logs"`
	Traces string `json:"traces"`
	Metrics string `json:"metrics"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityLayerSignalsDto AdminObservabilityLayerSignalsDto

// NewAdminObservabilityLayerSignalsDto instantiates a new AdminObservabilityLayerSignalsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityLayerSignalsDto(logs string, traces string, metrics string) *AdminObservabilityLayerSignalsDto {
	this := AdminObservabilityLayerSignalsDto{}
	this.Logs = logs
	this.Traces = traces
	this.Metrics = metrics
	return &this
}

// NewAdminObservabilityLayerSignalsDtoWithDefaults instantiates a new AdminObservabilityLayerSignalsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityLayerSignalsDtoWithDefaults() *AdminObservabilityLayerSignalsDto {
	this := AdminObservabilityLayerSignalsDto{}
	return &this
}

// GetLogs returns the Logs field value
func (o *AdminObservabilityLayerSignalsDto) GetLogs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerSignalsDto) GetLogsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Logs, true
}

// SetLogs sets field value
func (o *AdminObservabilityLayerSignalsDto) SetLogs(v string) {
	o.Logs = v
}

// GetTraces returns the Traces field value
func (o *AdminObservabilityLayerSignalsDto) GetTraces() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Traces
}

// GetTracesOk returns a tuple with the Traces field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerSignalsDto) GetTracesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Traces, true
}

// SetTraces sets field value
func (o *AdminObservabilityLayerSignalsDto) SetTraces(v string) {
	o.Traces = v
}

// GetMetrics returns the Metrics field value
func (o *AdminObservabilityLayerSignalsDto) GetMetrics() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityLayerSignalsDto) GetMetricsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *AdminObservabilityLayerSignalsDto) SetMetrics(v string) {
	o.Metrics = v
}

func (o AdminObservabilityLayerSignalsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityLayerSignalsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logs"] = o.Logs
	toSerialize["traces"] = o.Traces
	toSerialize["metrics"] = o.Metrics

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityLayerSignalsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logs",
		"traces",
		"metrics",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityLayerSignalsDto := _AdminObservabilityLayerSignalsDto{}

	err = json.Unmarshal(data, &varAdminObservabilityLayerSignalsDto)

	if err != nil {
		return err
	}

	*o = AdminObservabilityLayerSignalsDto(varAdminObservabilityLayerSignalsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "logs")
		delete(additionalProperties, "traces")
		delete(additionalProperties, "metrics")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityLayerSignalsDto struct {
	value *AdminObservabilityLayerSignalsDto
	isSet bool
}

func (v NullableAdminObservabilityLayerSignalsDto) Get() *AdminObservabilityLayerSignalsDto {
	return v.value
}

func (v *NullableAdminObservabilityLayerSignalsDto) Set(val *AdminObservabilityLayerSignalsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityLayerSignalsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityLayerSignalsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityLayerSignalsDto(val *AdminObservabilityLayerSignalsDto) *NullableAdminObservabilityLayerSignalsDto {
	return &NullableAdminObservabilityLayerSignalsDto{value: val, isSet: true}
}

func (v NullableAdminObservabilityLayerSignalsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityLayerSignalsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


