/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityXLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityXLog{}

// AdminObservabilityXLog struct for AdminObservabilityXLog
type AdminObservabilityXLog struct {
	Source string `json:"source"`
	Timestamp string `json:"timestamp"`
	ServiceName string `json:"serviceName"`
	Body string `json:"body"`
	SeverityText *string `json:"severityText,omitempty"`
	TraceId *string `json:"traceId,omitempty"`
	SpanId *string `json:"spanId,omitempty"`
	ExecutionId *string `json:"executionId,omitempty"`
	JobId *string `json:"jobId,omitempty"`
	Stream *string `json:"stream,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityXLog AdminObservabilityXLog

// NewAdminObservabilityXLog instantiates a new AdminObservabilityXLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityXLog(source string, timestamp string, serviceName string, body string) *AdminObservabilityXLog {
	this := AdminObservabilityXLog{}
	this.Source = source
	this.Timestamp = timestamp
	this.ServiceName = serviceName
	this.Body = body
	return &this
}

// NewAdminObservabilityXLogWithDefaults instantiates a new AdminObservabilityXLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityXLogWithDefaults() *AdminObservabilityXLog {
	this := AdminObservabilityXLog{}
	return &this
}

// GetSource returns the Source field value
func (o *AdminObservabilityXLog) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AdminObservabilityXLog) SetSource(v string) {
	o.Source = v
}

// GetTimestamp returns the Timestamp field value
func (o *AdminObservabilityXLog) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *AdminObservabilityXLog) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetServiceName returns the ServiceName field value
func (o *AdminObservabilityXLog) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *AdminObservabilityXLog) SetServiceName(v string) {
	o.ServiceName = v
}

// GetBody returns the Body field value
func (o *AdminObservabilityXLog) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *AdminObservabilityXLog) SetBody(v string) {
	o.Body = v
}

// GetSeverityText returns the SeverityText field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetSeverityText() string {
	if o == nil || IsNil(o.SeverityText) {
		var ret string
		return ret
	}
	return *o.SeverityText
}

// GetSeverityTextOk returns a tuple with the SeverityText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetSeverityTextOk() (*string, bool) {
	if o == nil || IsNil(o.SeverityText) {
		return nil, false
	}
	return o.SeverityText, true
}

// HasSeverityText returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasSeverityText() bool {
	if o != nil && !IsNil(o.SeverityText) {
		return true
	}

	return false
}

// SetSeverityText gets a reference to the given string and assigns it to the SeverityText field.
func (o *AdminObservabilityXLog) SetSeverityText(v string) {
	o.SeverityText = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *AdminObservabilityXLog) SetTraceId(v string) {
	o.TraceId = &v
}

// GetSpanId returns the SpanId field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetSpanId() string {
	if o == nil || IsNil(o.SpanId) {
		var ret string
		return ret
	}
	return *o.SpanId
}

// GetSpanIdOk returns a tuple with the SpanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetSpanIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpanId) {
		return nil, false
	}
	return o.SpanId, true
}

// HasSpanId returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasSpanId() bool {
	if o != nil && !IsNil(o.SpanId) {
		return true
	}

	return false
}

// SetSpanId gets a reference to the given string and assigns it to the SpanId field.
func (o *AdminObservabilityXLog) SetSpanId(v string) {
	o.SpanId = &v
}

// GetExecutionId returns the ExecutionId field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetExecutionId() string {
	if o == nil || IsNil(o.ExecutionId) {
		var ret string
		return ret
	}
	return *o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetExecutionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionId) {
		return nil, false
	}
	return o.ExecutionId, true
}

// HasExecutionId returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasExecutionId() bool {
	if o != nil && !IsNil(o.ExecutionId) {
		return true
	}

	return false
}

// SetExecutionId gets a reference to the given string and assigns it to the ExecutionId field.
func (o *AdminObservabilityXLog) SetExecutionId(v string) {
	o.ExecutionId = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *AdminObservabilityXLog) SetJobId(v string) {
	o.JobId = &v
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetStream() string {
	if o == nil || IsNil(o.Stream) {
		var ret string
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetStreamOk() (*string, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given string and assigns it to the Stream field.
func (o *AdminObservabilityXLog) SetStream(v string) {
	o.Stream = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *AdminObservabilityXLog) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityXLog) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *AdminObservabilityXLog) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *AdminObservabilityXLog) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o AdminObservabilityXLog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityXLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["serviceName"] = o.ServiceName
	toSerialize["body"] = o.Body
	if !IsNil(o.SeverityText) {
		toSerialize["severityText"] = o.SeverityText
	}
	if !IsNil(o.TraceId) {
		toSerialize["traceId"] = o.TraceId
	}
	if !IsNil(o.SpanId) {
		toSerialize["spanId"] = o.SpanId
	}
	if !IsNil(o.ExecutionId) {
		toSerialize["executionId"] = o.ExecutionId
	}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityXLog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"timestamp",
		"serviceName",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityXLog := _AdminObservabilityXLog{}

	err = json.Unmarshal(data, &varAdminObservabilityXLog)

	if err != nil {
		return err
	}

	*o = AdminObservabilityXLog(varAdminObservabilityXLog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "serviceName")
		delete(additionalProperties, "body")
		delete(additionalProperties, "severityText")
		delete(additionalProperties, "traceId")
		delete(additionalProperties, "spanId")
		delete(additionalProperties, "executionId")
		delete(additionalProperties, "jobId")
		delete(additionalProperties, "stream")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityXLog struct {
	value *AdminObservabilityXLog
	isSet bool
}

func (v NullableAdminObservabilityXLog) Get() *AdminObservabilityXLog {
	return v.value
}

func (v *NullableAdminObservabilityXLog) Set(val *AdminObservabilityXLog) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityXLog) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityXLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityXLog(val *AdminObservabilityXLog) *NullableAdminObservabilityXLog {
	return &NullableAdminObservabilityXLog{value: val, isSet: true}
}

func (v NullableAdminObservabilityXLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityXLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


