/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminOverviewRunners type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminOverviewRunners{}

// AdminOverviewRunners struct for AdminOverviewRunners
type AdminOverviewRunners struct {
	// Number of online (ready) runners
	Online float32 `json:"online"`
	// Total number of runners
	Total float32 `json:"total"`
	// Number of draining runners
	Draining float32 `json:"draining"`
	AdditionalProperties map[string]interface{}
}

type _AdminOverviewRunners AdminOverviewRunners

// NewAdminOverviewRunners instantiates a new AdminOverviewRunners object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminOverviewRunners(online float32, total float32, draining float32) *AdminOverviewRunners {
	this := AdminOverviewRunners{}
	this.Online = online
	this.Total = total
	this.Draining = draining
	return &this
}

// NewAdminOverviewRunnersWithDefaults instantiates a new AdminOverviewRunners object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminOverviewRunnersWithDefaults() *AdminOverviewRunners {
	this := AdminOverviewRunners{}
	return &this
}

// GetOnline returns the Online field value
func (o *AdminOverviewRunners) GetOnline() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *AdminOverviewRunners) GetOnlineOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *AdminOverviewRunners) SetOnline(v float32) {
	o.Online = v
}

// GetTotal returns the Total field value
func (o *AdminOverviewRunners) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AdminOverviewRunners) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AdminOverviewRunners) SetTotal(v float32) {
	o.Total = v
}

// GetDraining returns the Draining field value
func (o *AdminOverviewRunners) GetDraining() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Draining
}

// GetDrainingOk returns a tuple with the Draining field value
// and a boolean to check if the value has been set.
func (o *AdminOverviewRunners) GetDrainingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Draining, true
}

// SetDraining sets field value
func (o *AdminOverviewRunners) SetDraining(v float32) {
	o.Draining = v
}

func (o AdminOverviewRunners) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminOverviewRunners) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["online"] = o.Online
	toSerialize["total"] = o.Total
	toSerialize["draining"] = o.Draining

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminOverviewRunners) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"online",
		"total",
		"draining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminOverviewRunners := _AdminOverviewRunners{}

	err = json.Unmarshal(data, &varAdminOverviewRunners)

	if err != nil {
		return err
	}

	*o = AdminOverviewRunners(varAdminOverviewRunners)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "online")
		delete(additionalProperties, "total")
		delete(additionalProperties, "draining")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminOverviewRunners struct {
	value *AdminOverviewRunners
	isSet bool
}

func (v NullableAdminOverviewRunners) Get() *AdminOverviewRunners {
	return v.value
}

func (v *NullableAdminOverviewRunners) Set(val *AdminOverviewRunners) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminOverviewRunners) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminOverviewRunners) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminOverviewRunners(val *AdminOverviewRunners) *NullableAdminOverviewRunners {
	return &NullableAdminOverviewRunners{value: val, isSet: true}
}

func (v NullableAdminOverviewRunners) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminOverviewRunners) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


