/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityOperation{}

// AdminObservabilityOperation struct for AdminObservabilityOperation
type AdminObservabilityOperation struct {
	Id string `json:"id"`
	Label string `json:"label"`
	State string `json:"state"`
	Method string `json:"method"`
	Path string `json:"path"`
	Reason string `json:"reason"`
	TargetId *string `json:"targetId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityOperation AdminObservabilityOperation

// NewAdminObservabilityOperation instantiates a new AdminObservabilityOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityOperation(id string, label string, state string, method string, path string, reason string) *AdminObservabilityOperation {
	this := AdminObservabilityOperation{}
	this.Id = id
	this.Label = label
	this.State = state
	this.Method = method
	this.Path = path
	this.Reason = reason
	return &this
}

// NewAdminObservabilityOperationWithDefaults instantiates a new AdminObservabilityOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityOperationWithDefaults() *AdminObservabilityOperation {
	this := AdminObservabilityOperation{}
	return &this
}

// GetId returns the Id field value
func (o *AdminObservabilityOperation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AdminObservabilityOperation) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *AdminObservabilityOperation) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *AdminObservabilityOperation) SetLabel(v string) {
	o.Label = v
}

// GetState returns the State field value
func (o *AdminObservabilityOperation) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *AdminObservabilityOperation) SetState(v string) {
	o.State = v
}

// GetMethod returns the Method field value
func (o *AdminObservabilityOperation) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *AdminObservabilityOperation) SetMethod(v string) {
	o.Method = v
}

// GetPath returns the Path field value
func (o *AdminObservabilityOperation) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AdminObservabilityOperation) SetPath(v string) {
	o.Path = v
}

// GetReason returns the Reason field value
func (o *AdminObservabilityOperation) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *AdminObservabilityOperation) SetReason(v string) {
	o.Reason = v
}

// GetTargetId returns the TargetId field value if set, zero value otherwise.
func (o *AdminObservabilityOperation) GetTargetId() string {
	if o == nil || IsNil(o.TargetId) {
		var ret string
		return ret
	}
	return *o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityOperation) GetTargetIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetId) {
		return nil, false
	}
	return o.TargetId, true
}

// HasTargetId returns a boolean if a field has been set.
func (o *AdminObservabilityOperation) HasTargetId() bool {
	if o != nil && !IsNil(o.TargetId) {
		return true
	}

	return false
}

// SetTargetId gets a reference to the given string and assigns it to the TargetId field.
func (o *AdminObservabilityOperation) SetTargetId(v string) {
	o.TargetId = &v
}

func (o AdminObservabilityOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["state"] = o.State
	toSerialize["method"] = o.Method
	toSerialize["path"] = o.Path
	toSerialize["reason"] = o.Reason
	if !IsNil(o.TargetId) {
		toSerialize["targetId"] = o.TargetId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"state",
		"method",
		"path",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityOperation := _AdminObservabilityOperation{}

	err = json.Unmarshal(data, &varAdminObservabilityOperation)

	if err != nil {
		return err
	}

	*o = AdminObservabilityOperation(varAdminObservabilityOperation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "state")
		delete(additionalProperties, "method")
		delete(additionalProperties, "path")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "targetId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityOperation struct {
	value *AdminObservabilityOperation
	isSet bool
}

func (v NullableAdminObservabilityOperation) Get() *AdminObservabilityOperation {
	return v.value
}

func (v *NullableAdminObservabilityOperation) Set(val *AdminObservabilityOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityOperation(val *AdminObservabilityOperation) *NullableAdminObservabilityOperation {
	return &NullableAdminObservabilityOperation{value: val, isSet: true}
}

func (v NullableAdminObservabilityOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


