/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityInvestigateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityInvestigateResponse{}

// AdminObservabilityInvestigateResponse struct for AdminObservabilityInvestigateResponse
type AdminObservabilityInvestigateResponse struct {
	Resource AdminObservabilityResourceSummary `json:"resource"`
	Correlation AdminObservabilityCorrelation `json:"correlation"`
	Sources []AdminObservabilitySourceStatus `json:"sources"`
	TraceSpans []TraceSpan `json:"traceSpans"`
	Logs []LogEntry `json:"logs"`
	Metrics MetricsResponse `json:"metrics"`
	Boxes []AdminBoxItem `json:"boxes"`
	Runners []AdminRunnerItem `json:"runners"`
	Machines []AdminMachineItem `json:"machines"`
	AuditLogs []AdminObservabilityAuditLog `json:"auditLogs"`
	Xlogs []AdminObservabilityXLog `json:"xlogs"`
	S3Objects []AdminObservabilityS3Object `json:"s3Objects"`
	Timeline []AdminObservabilityTimelineEvent `json:"timeline"`
	Operations []AdminObservabilityOperation `json:"operations"`
	Commands AdminObservabilityCommands `json:"commands"`
	ExternalLinks AdminObservabilityExternalLinks `json:"externalLinks"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityInvestigateResponse AdminObservabilityInvestigateResponse

// NewAdminObservabilityInvestigateResponse instantiates a new AdminObservabilityInvestigateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityInvestigateResponse(resource AdminObservabilityResourceSummary, correlation AdminObservabilityCorrelation, sources []AdminObservabilitySourceStatus, traceSpans []TraceSpan, logs []LogEntry, metrics MetricsResponse, boxes []AdminBoxItem, runners []AdminRunnerItem, machines []AdminMachineItem, auditLogs []AdminObservabilityAuditLog, xlogs []AdminObservabilityXLog, s3Objects []AdminObservabilityS3Object, timeline []AdminObservabilityTimelineEvent, operations []AdminObservabilityOperation, commands AdminObservabilityCommands, externalLinks AdminObservabilityExternalLinks) *AdminObservabilityInvestigateResponse {
	this := AdminObservabilityInvestigateResponse{}
	this.Resource = resource
	this.Correlation = correlation
	this.Sources = sources
	this.TraceSpans = traceSpans
	this.Logs = logs
	this.Metrics = metrics
	this.Boxes = boxes
	this.Runners = runners
	this.Machines = machines
	this.AuditLogs = auditLogs
	this.Xlogs = xlogs
	this.S3Objects = s3Objects
	this.Timeline = timeline
	this.Operations = operations
	this.Commands = commands
	this.ExternalLinks = externalLinks
	return &this
}

// NewAdminObservabilityInvestigateResponseWithDefaults instantiates a new AdminObservabilityInvestigateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityInvestigateResponseWithDefaults() *AdminObservabilityInvestigateResponse {
	this := AdminObservabilityInvestigateResponse{}
	return &this
}

// GetResource returns the Resource field value
func (o *AdminObservabilityInvestigateResponse) GetResource() AdminObservabilityResourceSummary {
	if o == nil {
		var ret AdminObservabilityResourceSummary
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetResourceOk() (*AdminObservabilityResourceSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *AdminObservabilityInvestigateResponse) SetResource(v AdminObservabilityResourceSummary) {
	o.Resource = v
}

// GetCorrelation returns the Correlation field value
func (o *AdminObservabilityInvestigateResponse) GetCorrelation() AdminObservabilityCorrelation {
	if o == nil {
		var ret AdminObservabilityCorrelation
		return ret
	}

	return o.Correlation
}

// GetCorrelationOk returns a tuple with the Correlation field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetCorrelationOk() (*AdminObservabilityCorrelation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Correlation, true
}

// SetCorrelation sets field value
func (o *AdminObservabilityInvestigateResponse) SetCorrelation(v AdminObservabilityCorrelation) {
	o.Correlation = v
}

// GetSources returns the Sources field value
func (o *AdminObservabilityInvestigateResponse) GetSources() []AdminObservabilitySourceStatus {
	if o == nil {
		var ret []AdminObservabilitySourceStatus
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetSourcesOk() ([]AdminObservabilitySourceStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *AdminObservabilityInvestigateResponse) SetSources(v []AdminObservabilitySourceStatus) {
	o.Sources = v
}

// GetTraceSpans returns the TraceSpans field value
func (o *AdminObservabilityInvestigateResponse) GetTraceSpans() []TraceSpan {
	if o == nil {
		var ret []TraceSpan
		return ret
	}

	return o.TraceSpans
}

// GetTraceSpansOk returns a tuple with the TraceSpans field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetTraceSpansOk() ([]TraceSpan, bool) {
	if o == nil {
		return nil, false
	}
	return o.TraceSpans, true
}

// SetTraceSpans sets field value
func (o *AdminObservabilityInvestigateResponse) SetTraceSpans(v []TraceSpan) {
	o.TraceSpans = v
}

// GetLogs returns the Logs field value
func (o *AdminObservabilityInvestigateResponse) GetLogs() []LogEntry {
	if o == nil {
		var ret []LogEntry
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetLogsOk() ([]LogEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *AdminObservabilityInvestigateResponse) SetLogs(v []LogEntry) {
	o.Logs = v
}

// GetMetrics returns the Metrics field value
func (o *AdminObservabilityInvestigateResponse) GetMetrics() MetricsResponse {
	if o == nil {
		var ret MetricsResponse
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetMetricsOk() (*MetricsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *AdminObservabilityInvestigateResponse) SetMetrics(v MetricsResponse) {
	o.Metrics = v
}

// GetBoxes returns the Boxes field value
func (o *AdminObservabilityInvestigateResponse) GetBoxes() []AdminBoxItem {
	if o == nil {
		var ret []AdminBoxItem
		return ret
	}

	return o.Boxes
}

// GetBoxesOk returns a tuple with the Boxes field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetBoxesOk() ([]AdminBoxItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Boxes, true
}

// SetBoxes sets field value
func (o *AdminObservabilityInvestigateResponse) SetBoxes(v []AdminBoxItem) {
	o.Boxes = v
}

// GetRunners returns the Runners field value
func (o *AdminObservabilityInvestigateResponse) GetRunners() []AdminRunnerItem {
	if o == nil {
		var ret []AdminRunnerItem
		return ret
	}

	return o.Runners
}

// GetRunnersOk returns a tuple with the Runners field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetRunnersOk() ([]AdminRunnerItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Runners, true
}

// SetRunners sets field value
func (o *AdminObservabilityInvestigateResponse) SetRunners(v []AdminRunnerItem) {
	o.Runners = v
}

// GetMachines returns the Machines field value
func (o *AdminObservabilityInvestigateResponse) GetMachines() []AdminMachineItem {
	if o == nil {
		var ret []AdminMachineItem
		return ret
	}

	return o.Machines
}

// GetMachinesOk returns a tuple with the Machines field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetMachinesOk() ([]AdminMachineItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Machines, true
}

// SetMachines sets field value
func (o *AdminObservabilityInvestigateResponse) SetMachines(v []AdminMachineItem) {
	o.Machines = v
}

// GetAuditLogs returns the AuditLogs field value
func (o *AdminObservabilityInvestigateResponse) GetAuditLogs() []AdminObservabilityAuditLog {
	if o == nil {
		var ret []AdminObservabilityAuditLog
		return ret
	}

	return o.AuditLogs
}

// GetAuditLogsOk returns a tuple with the AuditLogs field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetAuditLogsOk() ([]AdminObservabilityAuditLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditLogs, true
}

// SetAuditLogs sets field value
func (o *AdminObservabilityInvestigateResponse) SetAuditLogs(v []AdminObservabilityAuditLog) {
	o.AuditLogs = v
}

// GetXlogs returns the Xlogs field value
func (o *AdminObservabilityInvestigateResponse) GetXlogs() []AdminObservabilityXLog {
	if o == nil {
		var ret []AdminObservabilityXLog
		return ret
	}

	return o.Xlogs
}

// GetXlogsOk returns a tuple with the Xlogs field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetXlogsOk() ([]AdminObservabilityXLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Xlogs, true
}

// SetXlogs sets field value
func (o *AdminObservabilityInvestigateResponse) SetXlogs(v []AdminObservabilityXLog) {
	o.Xlogs = v
}

// GetS3Objects returns the S3Objects field value
func (o *AdminObservabilityInvestigateResponse) GetS3Objects() []AdminObservabilityS3Object {
	if o == nil {
		var ret []AdminObservabilityS3Object
		return ret
	}

	return o.S3Objects
}

// GetS3ObjectsOk returns a tuple with the S3Objects field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetS3ObjectsOk() ([]AdminObservabilityS3Object, bool) {
	if o == nil {
		return nil, false
	}
	return o.S3Objects, true
}

// SetS3Objects sets field value
func (o *AdminObservabilityInvestigateResponse) SetS3Objects(v []AdminObservabilityS3Object) {
	o.S3Objects = v
}

// GetTimeline returns the Timeline field value
func (o *AdminObservabilityInvestigateResponse) GetTimeline() []AdminObservabilityTimelineEvent {
	if o == nil {
		var ret []AdminObservabilityTimelineEvent
		return ret
	}

	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetTimelineOk() ([]AdminObservabilityTimelineEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeline, true
}

// SetTimeline sets field value
func (o *AdminObservabilityInvestigateResponse) SetTimeline(v []AdminObservabilityTimelineEvent) {
	o.Timeline = v
}

// GetOperations returns the Operations field value
func (o *AdminObservabilityInvestigateResponse) GetOperations() []AdminObservabilityOperation {
	if o == nil {
		var ret []AdminObservabilityOperation
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetOperationsOk() ([]AdminObservabilityOperation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operations, true
}

// SetOperations sets field value
func (o *AdminObservabilityInvestigateResponse) SetOperations(v []AdminObservabilityOperation) {
	o.Operations = v
}

// GetCommands returns the Commands field value
func (o *AdminObservabilityInvestigateResponse) GetCommands() AdminObservabilityCommands {
	if o == nil {
		var ret AdminObservabilityCommands
		return ret
	}

	return o.Commands
}

// GetCommandsOk returns a tuple with the Commands field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetCommandsOk() (*AdminObservabilityCommands, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Commands, true
}

// SetCommands sets field value
func (o *AdminObservabilityInvestigateResponse) SetCommands(v AdminObservabilityCommands) {
	o.Commands = v
}

// GetExternalLinks returns the ExternalLinks field value
func (o *AdminObservabilityInvestigateResponse) GetExternalLinks() AdminObservabilityExternalLinks {
	if o == nil {
		var ret AdminObservabilityExternalLinks
		return ret
	}

	return o.ExternalLinks
}

// GetExternalLinksOk returns a tuple with the ExternalLinks field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityInvestigateResponse) GetExternalLinksOk() (*AdminObservabilityExternalLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalLinks, true
}

// SetExternalLinks sets field value
func (o *AdminObservabilityInvestigateResponse) SetExternalLinks(v AdminObservabilityExternalLinks) {
	o.ExternalLinks = v
}

func (o AdminObservabilityInvestigateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityInvestigateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource"] = o.Resource
	toSerialize["correlation"] = o.Correlation
	toSerialize["sources"] = o.Sources
	toSerialize["traceSpans"] = o.TraceSpans
	toSerialize["logs"] = o.Logs
	toSerialize["metrics"] = o.Metrics
	toSerialize["boxes"] = o.Boxes
	toSerialize["runners"] = o.Runners
	toSerialize["machines"] = o.Machines
	toSerialize["auditLogs"] = o.AuditLogs
	toSerialize["xlogs"] = o.Xlogs
	toSerialize["s3Objects"] = o.S3Objects
	toSerialize["timeline"] = o.Timeline
	toSerialize["operations"] = o.Operations
	toSerialize["commands"] = o.Commands
	toSerialize["externalLinks"] = o.ExternalLinks

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityInvestigateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource",
		"correlation",
		"sources",
		"traceSpans",
		"logs",
		"metrics",
		"boxes",
		"runners",
		"machines",
		"auditLogs",
		"xlogs",
		"s3Objects",
		"timeline",
		"operations",
		"commands",
		"externalLinks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityInvestigateResponse := _AdminObservabilityInvestigateResponse{}

	err = json.Unmarshal(data, &varAdminObservabilityInvestigateResponse)

	if err != nil {
		return err
	}

	*o = AdminObservabilityInvestigateResponse(varAdminObservabilityInvestigateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "resource")
		delete(additionalProperties, "correlation")
		delete(additionalProperties, "sources")
		delete(additionalProperties, "traceSpans")
		delete(additionalProperties, "logs")
		delete(additionalProperties, "metrics")
		delete(additionalProperties, "boxes")
		delete(additionalProperties, "runners")
		delete(additionalProperties, "machines")
		delete(additionalProperties, "auditLogs")
		delete(additionalProperties, "xlogs")
		delete(additionalProperties, "s3Objects")
		delete(additionalProperties, "timeline")
		delete(additionalProperties, "operations")
		delete(additionalProperties, "commands")
		delete(additionalProperties, "externalLinks")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityInvestigateResponse struct {
	value *AdminObservabilityInvestigateResponse
	isSet bool
}

func (v NullableAdminObservabilityInvestigateResponse) Get() *AdminObservabilityInvestigateResponse {
	return v.value
}

func (v *NullableAdminObservabilityInvestigateResponse) Set(val *AdminObservabilityInvestigateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityInvestigateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityInvestigateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityInvestigateResponse(val *AdminObservabilityInvestigateResponse) *NullableAdminObservabilityInvestigateResponse {
	return &NullableAdminObservabilityInvestigateResponse{value: val, isSet: true}
}

func (v NullableAdminObservabilityInvestigateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityInvestigateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


