/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminObservabilityBackendStatusDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminObservabilityBackendStatusDto{}

// AdminObservabilityBackendStatusDto struct for AdminObservabilityBackendStatusDto
type AdminObservabilityBackendStatusDto struct {
	// Whether ClickHouse/ClickStack query configuration is present
	Configured bool `json:"configured"`
	State string `json:"state"`
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdminObservabilityBackendStatusDto AdminObservabilityBackendStatusDto

// NewAdminObservabilityBackendStatusDto instantiates a new AdminObservabilityBackendStatusDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminObservabilityBackendStatusDto(configured bool, state string) *AdminObservabilityBackendStatusDto {
	this := AdminObservabilityBackendStatusDto{}
	this.Configured = configured
	this.State = state
	return &this
}

// NewAdminObservabilityBackendStatusDtoWithDefaults instantiates a new AdminObservabilityBackendStatusDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminObservabilityBackendStatusDtoWithDefaults() *AdminObservabilityBackendStatusDto {
	this := AdminObservabilityBackendStatusDto{}
	return &this
}

// GetConfigured returns the Configured field value
func (o *AdminObservabilityBackendStatusDto) GetConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityBackendStatusDto) GetConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configured, true
}

// SetConfigured sets field value
func (o *AdminObservabilityBackendStatusDto) SetConfigured(v bool) {
	o.Configured = v
}

// GetState returns the State field value
func (o *AdminObservabilityBackendStatusDto) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *AdminObservabilityBackendStatusDto) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *AdminObservabilityBackendStatusDto) SetState(v string) {
	o.State = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AdminObservabilityBackendStatusDto) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminObservabilityBackendStatusDto) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AdminObservabilityBackendStatusDto) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AdminObservabilityBackendStatusDto) SetMessage(v string) {
	o.Message = &v
}

func (o AdminObservabilityBackendStatusDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminObservabilityBackendStatusDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configured"] = o.Configured
	toSerialize["state"] = o.State
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminObservabilityBackendStatusDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configured",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminObservabilityBackendStatusDto := _AdminObservabilityBackendStatusDto{}

	err = json.Unmarshal(data, &varAdminObservabilityBackendStatusDto)

	if err != nil {
		return err
	}

	*o = AdminObservabilityBackendStatusDto(varAdminObservabilityBackendStatusDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "configured")
		delete(additionalProperties, "state")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminObservabilityBackendStatusDto struct {
	value *AdminObservabilityBackendStatusDto
	isSet bool
}

func (v NullableAdminObservabilityBackendStatusDto) Get() *AdminObservabilityBackendStatusDto {
	return v.value
}

func (v *NullableAdminObservabilityBackendStatusDto) Set(val *AdminObservabilityBackendStatusDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminObservabilityBackendStatusDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminObservabilityBackendStatusDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminObservabilityBackendStatusDto(val *AdminObservabilityBackendStatusDto) *NullableAdminObservabilityBackendStatusDto {
	return &NullableAdminObservabilityBackendStatusDto{value: val, isSet: true}
}

func (v NullableAdminObservabilityBackendStatusDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminObservabilityBackendStatusDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


