/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AdminOverviewBoxes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminOverviewBoxes{}

// AdminOverviewBoxes struct for AdminOverviewBoxes
type AdminOverviewBoxes struct {
	// Total number of boxes across all states
	Total float32 `json:"total"`
	// Box counts keyed by BoxState
	ByState map[string]float32 `json:"byState"`
	AdditionalProperties map[string]interface{}
}

type _AdminOverviewBoxes AdminOverviewBoxes

// NewAdminOverviewBoxes instantiates a new AdminOverviewBoxes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminOverviewBoxes(total float32, byState map[string]float32) *AdminOverviewBoxes {
	this := AdminOverviewBoxes{}
	this.Total = total
	this.ByState = byState
	return &this
}

// NewAdminOverviewBoxesWithDefaults instantiates a new AdminOverviewBoxes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminOverviewBoxesWithDefaults() *AdminOverviewBoxes {
	this := AdminOverviewBoxes{}
	return &this
}

// GetTotal returns the Total field value
func (o *AdminOverviewBoxes) GetTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AdminOverviewBoxes) GetTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AdminOverviewBoxes) SetTotal(v float32) {
	o.Total = v
}

// GetByState returns the ByState field value
func (o *AdminOverviewBoxes) GetByState() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.ByState
}

// GetByStateOk returns a tuple with the ByState field value
// and a boolean to check if the value has been set.
func (o *AdminOverviewBoxes) GetByStateOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ByState, true
}

// SetByState sets field value
func (o *AdminOverviewBoxes) SetByState(v map[string]float32) {
	o.ByState = v
}

func (o AdminOverviewBoxes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminOverviewBoxes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["byState"] = o.ByState

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdminOverviewBoxes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"byState",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminOverviewBoxes := _AdminOverviewBoxes{}

	err = json.Unmarshal(data, &varAdminOverviewBoxes)

	if err != nil {
		return err
	}

	*o = AdminOverviewBoxes(varAdminOverviewBoxes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total")
		delete(additionalProperties, "byState")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdminOverviewBoxes struct {
	value *AdminOverviewBoxes
	isSet bool
}

func (v NullableAdminOverviewBoxes) Get() *AdminOverviewBoxes {
	return v.value
}

func (v *NullableAdminOverviewBoxes) Set(val *AdminOverviewBoxes) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminOverviewBoxes) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminOverviewBoxes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminOverviewBoxes(val *AdminOverviewBoxes) *NullableAdminOverviewBoxes {
	return &NullableAdminOverviewBoxes{value: val, isSet: true}
}

func (v NullableAdminOverviewBoxes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminOverviewBoxes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


